apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: perflow-secrets
  namespace: perflow
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: DB_PORT         # 쿠버네티스 Secret에서의 key 이름
      remoteRef:
        key: perflow/API-KEY     # AWS Secrets Manager에서의 비밀 이름
        property: db.port        # 해당 JSON 경로
    - secretKey: DB_NAME
      remoteRef:
        key: perflow/API-KEY
        property: db.name
    - secretKey: DB_USER
      remoteRef:
        key: perflow/API-KEY
        property: db.user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: perflow/API-KEY
        property: db.password
    - secretKey: DB_HOST
      remoteRef:
        key: perflow/API-KEY
        property: db.host
    - secretKey: JWT_SECRET
      remoteRef:
        key: perflow/API-KEY
        property: token.secret
    - secretKey: JWT_ACCESS_TOKEN_EXPIRATION_TIME
      remoteRef:
        key: perflow/API-KEY
        property: token.access_token_expiration_time
    - secretKey: JWT_REFRESH_TOKEN_EXPIRATION_TIME
      remoteRef:
        key: perflow/API-KEY
        property: token.refresh_token_expiration_time
    - secretKey: JWT_EMAIL_TOKEN_EXPIRATION_TIME
      remoteRef:
        key: perflow/API-KEY
        property: token.email_token_expiration_time
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: perflow/API-KEY
        property: spring.mail.username
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: perflow/API-KEY
        property: spring.mail.password
    - secretKey: MAIL_PORT
      remoteRef:
        key: perflow/API-KEY
        property: spring.mail.port
    - secretKey: AWS_ACCESS_KEY
      remoteRef:
        key: perflow/API-KEY
        property: aws.access
    - secretKey: AWS_SECRET_KEY
      remoteRef:
        key: perflow/API-KEY
        property: aws.secret
    - secretKey: AWS_BUCKET_NAME
      remoteRef:
        key: perflow/API-KEY
        property: aws.bucket
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: perflow/API-KEY
        property: gemini.api.key
    - secretKey: GEMINI_API_URL
      remoteRef:
        key: perflow/API-KEY
        property: gemini.api.url
    - secretKey: GEMINI_MODEL_NAME
      remoteRef:
        key: perflow/API-KEY
        property: gemini.api.model
    - secretKey: RABBIT_MQ_HOST
      remoteRef:
        key: perflow/API-KEY
        property: rabbitMQ.host
    - secretKey: RABBIT_MQ_USERNAME
      remoteRef:
        key: perflow/API-KEY
        property: rabbitMQ.username
    - secretKey: RABBIT_MQ_PASSWORD
      remoteRef:
        key: perflow/API-KEY
        property: rabbitMQ.password
    - secretKey: FCM_TYPE
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.type
    - secretKey: FCM_PROJECT_ID
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.project_id
    - secretKey: FCM_PRIVATE_KEY_ID
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.private_key_id
    - secretKey: FCM_PRIVATE_KEY
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.private_key
    - secretKey: FCM_CLIENT_EMAIL
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.client_email
    - secretKey: FCM_CLIENT_ID
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.client_id
    - secretKey: FCM_AUTH_URI
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.auth_uri
    - secretKey: FCM_TOKEN_URI
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.token_uri
    - secretKey: FCM_AUTH_PROVIDER_X509_CERT_URL
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.auth_provider_x509_cert_url
    - secretKey: FCM_CLIENT_X509_CERT_URL
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.client_x509_cert_url
    - secretKey: FCM_UNIVERSE_DOMAIN
      remoteRef:
        key: perflow/API-KEY
        property: fcm.service-account.universe_domain
    - secretKey: AES_SECRET
      remoteRef:
        key: perflow/API-KEY
        property: aesSecret
  target:
    name: perflow-secrets
    creationPolicy: Owner
