apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: perflow-secrets
  namespace: perflow
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: DB_PORT         # 쿠버네티스 Secret에서의 key 이름
      remoteRef:
        key: perflow/API-KEY     # AWS Secrets Manager에서의 비밀 이름
        property: db.port        # 해당 JSON 경로
    - secretKey: DB_NAME
      remoteRef:
        key: perflow/API-KEY
        property: db.name
    - secretKey: DB_USER
      remoteRef:
        key: perflow/API-KEY
        property: db.user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: perflow/API-KEY
        property: db.password
    - secretKey: JWT_SECRET
      remoteRef:
        key: perflow/API-KEY
        property: token.secret
    - secretKey: JWT_ACCESS_TOKEN_EXPIRATION_TIME
      remoteRef:
        key: perflow/API-KEY
        property: token.access_token_expiration_time
    - secretKey: JWT_REFRESH_TOKEN_EXPIRATION_TIME
      remoteRef:
        key: perflow/API-KEY
        property: token.refresh_token_expiration_time
    - secretKey: JWT_EMAIL_TOKEN_EXPIRATION_TIME
      remoteRef:
        key: perflow/API-KEY
        property: token.email_token_expiration_time
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: perflow/API-KEY
        property: spring.mail.username
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: perflow/API-KEY
        property: spring.mail.password
    - secretKey: MAIL_PORT
      remoteRef:
        key: perflow/API-KEY
        property: spring.mail.port
    - secretKey: AWS_ACCESS_KEY
      remoteRef:
        key: perflow/API-KEY
        property: aws.access
    - secretKey: AWS_SECRET_KEY
      remoteRef:
        key: perflow/API-KEY
        property: aws.secret
    - secretKey: AWS_BUCKET_NAME
      remoteRef:
        key: perflow/API-KEY
        property: aws.bucket
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: perflow/API-KEY
        property: gemini.api.key
    - secretKey: GEMINI_API_URL
      remoteRef:
        key: perflow/API-KEY
        property: gemini.api.url
    - secretKey: GEMINI_MODEL_NAME
      remoteRef:
        key: perflow/API-KEY
        property: gemini.api.model
  target:
    name: perflow-secrets
    creationPolicy: Owner
