apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: perflow-secrets # 생성될 ExternalSecret 이름 (고유해야 함)
  namespace: external-secrets # Secret이 생성될 네임스페이스
spec:
  secretStoreRef:
    name: aws-secrets-manager # 이전에 생성한 ClusterSecretStore 이름
    kind: ClusterSecretStore
  data:
    - key: perflow/API-KEY # Secrets Manager의 Secret 이름
      name: DB_PORT # 생성될 Kubernetes Secret의 키 이름 (환경변수명으로 사용하기 적합)
      property: db.port # Secrets Manager JSON 데이터의 경로 (JSONPath)
    - key: perflow/API-KEY
      name: DB_NAME
      property: db.name
    - key: perflow/API-KEY
      name: DB_USER
      property: db.user
    - key: perflow/API-KEY
      name: DB_PASSWORD
      property: db.password
    - key: perflow/API-KEY
      name: JWT_SECRET # JWT secret 추가
      property: token.secret
    - key: perflow/API-KEY
      name: MAIL_USERNAME # mail username 추가
      property: spring.mail.username
    - key: perflow/API-KEY
      name: MAIL_PASSWORD # mail password 추가
      property: spring.mail.password
    - key: perflow/API-KEY
      name: MAIL_PORT # mail port 추가
      property: spring.mail.port
    - key: perflow/API-KEY
      name: AWS_ACCESS_KEY # AWS access key 추가
      property: aws.access
    - key: perflow/API-KEY
      name: AWS_SECRET_KEY # AWS secret key 추가
      property: aws.secret
    - key: perflow/API-KEY
      name: AWS_BUCKET_NAME # AWS bucket name 추가
      property: aws.bucket
    - key: perflow/API-KEY # Gemini API key 추가
      name: GEMINI_API_KEY
      property: gemini.api.key
    - key: perflow/API-KEY # Gemini API url 추가
      name: GEMINI_API_URL
      property: gemini.api.url
    - key: perflow/API-KEY # Gemini model name 추가
      name: GEMINI_MODEL_NAME
      property: gemini.api.model
  target:
    name: perflow-api-key # 생성될 Kubernetes Secret 이름
    creationPolicy: Owner # ExternalSecret 삭제 시 Secret도 함께 삭제