apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: perflow
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672 # RabbitMQ communication port
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672 # RabbitMQ Management UI port
      targetPort: 15672
  type: ClusterIP
