# external-secrets/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: perflow
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::851725312801:role/AmazonEKSAutoClusterRole
